[package]
name = "mme"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
thiserror = "1"
# local path dependencies
nas = { path = "../nas" }
rrc = { path = "../rrc" }
s1ap = { path = "../s1ap" }
